# Generated by Django 5.2.4 on 2025-07-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_list_listitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='product',
        ),
        migrations.AddField(
            model_name='listitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='platform',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listitem',
            name='price',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listitem',
            name='product_title',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listitem',
            name='product_url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listitem',
            name='rating',
            field=models.CharField(default=0.0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listitem',
            name='shop_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
